name: Build & Deploy Visal Brokers Website
on:
  push:
    branches:
      - main
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.20.0"
  build:
    name: Build & Deploy
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.20.0"
      - name: Install Dependencies
        run: yarn install
      - name: 🔨 Build Project
        env:
          CI: true
        run: yarn build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ./out/*
          target: ${{ secrets.TARGET }}
          strip_components: 1
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
